version: '3'
services:
  redis:
    image: redis
    restart: always
    volumes:
      - redis:/data

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
    volumes:
      - postgres:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_replication_slots=2"

  superset:
    image: amancevice/superset
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
    ports:
      - "8088:8088"
    volumes:
      - ./superset_config.py:/etc/superset/superset_config.py

  clickhouse:
    build: clickhouse
    restart: always
    volumes:
      - clickhouse:/var/lib/clickhouse
      - ./odbc.ini:/etc/odbc.ini
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

  script:
    build: script
    volumes:
      - ./odbc.ini:/etc/odbc.ini # Create currect unixODBC DSN in ./odbc.ini
    env_file:
      - dsn.env

volumes:
  postgres:
  redis:
  clickhouse:
